# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindRestaurant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleMaps'
  pod 'SwiftyJSON'

  # Pods for FindRestaurant

end
